<x-layouts.app title="Registration Links — Foreign Employment">

<x-page-header
    title="Registration Links"
    subtitle="Manage secure one-time candidate registration links"
    :breadcrumbs="[['url' => route('dashboard'), 'label' => 'Dashboard'], ['url' => route('employment.dashboard'), 'label' => 'Employment'], ['url' => '#', 'label' => 'Registration Links']]">
    <x-slot:actions>
        <button class="btn btn-primary btn-sm" onclick="document.getElementById('new-link-modal').classList.remove('hidden')">
            <i data-lucide="link" style="width:14px;height:14px"></i>
            Generate New Link
        </button>
    </x-slot:actions>
</x-page-header>

<!-- Important info banner -->
<div class="alert alert-info mb-5">
    <i data-lucide="shield-check" style="width:18px;height:18px;flex-shrink:0"></i>
    <div>
        <p class="font-bold">Secure One-Time Registration Links</p>
        <p class="text-sm mt-0.5">Each link is unique, single-use, and expires automatically. A new link must be generated if a candidate does not complete registration before the expiry date.</p>
    </div>
</div>

<!-- Stats -->
<div class="grid grid-cols-2 md:grid-cols-6 gap-4 mb-6">
    <x-stat-card value="47"  label="Total Generated"  icon="link"       color="indigo" />
    <x-stat-card value="12"  label="Sent"             icon="send"       color="blue" />
    <x-stat-card value="9"   label="Opened"           icon="eye"        color="violet" />
    <x-stat-card value="31"  label="Completed"        icon="check-circle" color="emerald" />
    <x-stat-card value="3"   label="Expired"          icon="clock"      color="amber" />
    <x-stat-card value="2"   label="Cancelled"        icon="x-circle"   color="rose" />
</div>

<!-- Links Table -->
<div class="card">
    <div class="overflow-x-auto">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Link ID</th>
                    <th>Candidate / Contact</th>
                    <th>Generated By</th>
                    <th>Sent Via</th>
                    <th>Generated</th>
                    <th>Expires</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @php
                $links = [
                    ['id' => 'LNK-0047', 'name' => 'Roshan Wijesinghe',    'phone' => '077 456 7891', 'by' => 'Kasun B.', 'via' => 'WhatsApp', 'gen' => '06 Oct 2026', 'exp' => '13 Oct 2026', 'status' => 'sent',      'days_left' => 7],
                    ['id' => 'LNK-0046', 'name' => 'Malith Jayasekara',    'phone' => '071 900 1234', 'by' => 'Priya H.', 'via' => 'SMS',      'gen' => '05 Oct 2026', 'exp' => '12 Oct 2026', 'status' => 'opened',    'days_left' => 6],
                    ['id' => 'LNK-0045', 'name' => 'Chamali Abeywickrama', 'phone' => '076 543 2109', 'by' => 'Amila P.', 'via' => 'WhatsApp', 'gen' => '04 Oct 2026', 'exp' => '11 Oct 2026', 'status' => 'created',   'days_left' => 5],
                    ['id' => 'LNK-0044', 'name' => 'Thilini Madushan',     'phone' => '077 234 5678', 'by' => 'Kasun B.', 'via' => 'Email',    'gen' => '03 Oct 2026', 'exp' => '06 Oct 2026', 'status' => 'completed', 'days_left' => 0],
                    ['id' => 'LNK-0043', 'name' => 'Pradeep Siriwardena',  'phone' => '070 111 2222', 'by' => 'Nimal J.', 'via' => 'WhatsApp', 'gen' => '27 Sep 2026', 'exp' => '04 Oct 2026', 'status' => 'expired',   'days_left' => 0],
                    ['id' => 'LNK-0041', 'name' => 'Kumari Dissanayake',   'phone' => '071 333 4444', 'by' => 'Priya H.', 'via' => 'SMS',      'gen' => '22 Sep 2026', 'exp' => '29 Sep 2026', 'status' => 'completed', 'days_left' => 0],
                ];
                @endphp
                @foreach($links as $link)
                @php
                $sb = ['created' => 'badge-draft', 'sent' => 'badge-registered', 'opened' => 'badge-processing', 'completed' => 'badge-approved', 'expired' => 'badge-overdue', 'cancelled' => 'badge-closed'];
                $sl = ['created' => 'Created', 'sent' => 'Sent', 'opened' => 'Opened', 'completed' => 'Completed', 'expired' => 'Expired', 'cancelled' => 'Cancelled'];
                @endphp
                <tr class="{{ $link['status'] === 'expired' ? 'opacity-60' : '' }}">
                    <td>
                        <code class="text-sm font-mono text-indigo-600">{{ $link['id'] }}</code>
                    </td>
                    <td>
                        <div class="flex items-center gap-2">
                            <div class="avatar avatar-sm avatar-indigo">{{ substr($link['name'], 0, 2) }}</div>
                            <div>
                                <p class="text-sm font-semibold text-slate-800">{{ $link['name'] }}</p>
                                <p class="text-xs text-slate-400">{{ $link['phone'] }}</p>
                            </div>
                        </div>
                    </td>
                    <td class="text-sm text-slate-600">{{ $link['by'] }}</td>
                    <td>
                        <div class="flex items-center gap-1.5 text-sm text-slate-600">
                            @if($link['via'] === 'WhatsApp')
                                <svg width="14" height="14" viewBox="0 0 24 24" fill="#25D366"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/></svg>
                            @elseif($link['via'] === 'SMS')
                                <i data-lucide="message-square" style="width:13px;height:13px;color:#64748b"></i>
                            @else
                                <i data-lucide="mail" style="width:13px;height:13px;color:#64748b"></i>
                            @endif
                            {{ $link['via'] }}
                        </div>
                    </td>
                    <td class="text-sm text-slate-600">{{ $link['gen'] }}</td>
                    <td>
                        <div class="text-sm {{ $link['status'] === 'expired' ? 'text-rose-600 font-bold' : 'text-slate-600' }}">
                            {{ $link['exp'] }}
                            @if($link['days_left'] > 0)
                            <span class="text-xs text-slate-400 block">{{ $link['days_left'] }} days left</span>
                            @endif
                        </div>
                    </td>
                    <td>
                        <span class="badge {{ $sb[$link['status']] }} badge-dot">{{ $sl[$link['status']] }}</span>
                    </td>
                    <td>
                        <div class="flex items-center gap-1">
                            @if($link['status'] === 'expired')
                                <button class="btn btn-primary btn-xs">
                                    <i data-lucide="refresh-cw" style="width:11px;height:11px"></i>
                                    Regenerate
                                </button>
                            @elseif(in_array($link['status'], ['created', 'sent', 'opened']))
                                <button class="btn btn-ghost btn-xs" title="Copy link">
                                    <i data-lucide="copy" style="width:13px;height:13px"></i>
                                </button>
                                <button class="btn btn-ghost btn-xs" title="Resend">
                                    <i data-lucide="send" style="width:13px;height:13px"></i>
                                </button>
                            @endif
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

<!-- Generate Link Modal -->
<div id="new-link-modal" class="modal-overlay hidden">
    <div class="modal-box">
        <div class="modal-header">
            <h2 class="modal-title">Generate Registration Link</h2>
            <button class="modal-close" onclick="document.getElementById('new-link-modal').classList.add('hidden')">
                <i data-lucide="x" style="width:16px;height:16px"></i>
            </button>
        </div>
        <div class="modal-body space-y-4">
            <div class="alert alert-warning">
                <i data-lucide="shield" style="width:16px;height:16px;flex-shrink:0"></i>
                <p class="text-sm">This is a <strong>one-time secure link</strong>. Once the candidate completes registration, the link becomes invalid. Set a realistic expiry date.</p>
            </div>
            <div class="form-group">
                <label class="form-label required">Candidate / Contact Name</label>
                <input type="text" class="form-input" placeholder="Full name">
            </div>
            <div class="form-group">
                <label class="form-label required">Phone / WhatsApp</label>
                <input type="tel" class="form-input" placeholder="077 XXX XXXX">
            </div>
            <div class="form-group">
                <label class="form-label">Email (optional)</label>
                <input type="email" class="form-input" placeholder="email@example.com">
            </div>
            <div class="form-group">
                <label class="form-label required">Link Expiry</label>
                <select class="form-select">
                    <option>7 days</option>
                    <option>14 days</option>
                    <option>30 days</option>
                </select>
            </div>
            <div class="form-group">
                <label class="form-label required">Send Via</label>
                <div class="flex gap-3">
                    <label class="flex items-center gap-2 text-sm cursor-pointer">
                        <input type="checkbox" class="form-input" style="width:14px;height:14px;padding:0" checked> WhatsApp
                    </label>
                    <label class="flex items-center gap-2 text-sm cursor-pointer">
                        <input type="checkbox" class="form-input" style="width:14px;height:14px;padding:0"> SMS
                    </label>
                    <label class="flex items-center gap-2 text-sm cursor-pointer">
                        <input type="checkbox" class="form-input" style="width:14px;height:14px;padding:0"> Email
                    </label>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-secondary" onclick="document.getElementById('new-link-modal').classList.add('hidden')">Cancel</button>
            <button class="btn btn-primary">
                <i data-lucide="link" style="width:14px;height:14px"></i>
                Generate & Send Link
            </button>
        </div>
    </div>
</div>

<script>document.addEventListener('DOMContentLoaded', () => lucide.createIcons());</script>
</x-layouts.app>
