memory_limit = 512M
extension_dir = "C:\Program Files\php-8.5.1-Win32-vs17-x64\ext"
extension="C:\Program Files\php-8.5.1-Win32-vs17-x64\ext\php_pdo_sqlite.dll"
extension="C:\Program Files\php-8.5.1-Win32-vs17-x64\ext\php_sqlite3.dll"
